### ISSUE TITLE
Intermediate Format

### ISSUE THREAD

**Issue by fab1an** [flow-atom/flow-electron-api#17]
Do you generate this API automatically from somewhere? Is there an intermediate format, I can use to create Kotlin-bindings?

**Comment by freebroccolo** [comment]
No, unfortunately it was created by hand and is still missing some stuff I think. I don't know of any clean way to automatically generate it.

**Comment by fab1an** [comment]
If you know your way around XSLT/xpath, check this out: https://github.com/fab1an/kotlin-electron-api/blob/master/README.md

You should be able the output of the third step (`normalized.xml`).

There's still work to be done on events, properties and such though.

**Comment by fab1an** [comment]
I uploaded the xml files now as well: https://github.com/fab1an/kotlin-electron-api/blob/master/build/api_docbook/browser-window.source.normalized.xml
